name: LoupGarou
version: v1.0.16
description: Plugin de loup garou
author: Ekinoxx

main: dev.loupgarou.MainLg
depend: [ProtocolLib]
api-version: 1.13

commands:
  lg:
    description: Gestion de la configuration et accès aux menus
    aliases: [loup, loupgarou]

permissions:
  loupgarou.admin:
    description: Administration du plugin
    default: op