name: LoupGarou
version: v1.4.12
description: Plugin de loup garou
author: Ekinoxx
website: https://github.com/Ekinoxx0/LoupGarou

main: dev.loupgarou.MainLg
depend: [ProtocolLib, AuthMe]
api-version: 1.13

commands:
  lg:
    description: Gestion de la configuration et accès aux menus
    aliases: [loup, loupgarou]
  join:
  autorole:
  menu:
  start:
  end:
  leave:
  spawn:
  hub:
  lobby:
  quit:
  discord:
  discordlink:

permissions:
  loupgarou.*:
    default: op
    description: Administration du plugin
    children:
      loupgarou.cmd: true
      loupgarou.cmd.*: true
  loupgarou.cmd.*:
    default: op
    description: Administration par commande du plugin
    children:
      loupgarou.cmd.roles: true